var cityData=[
	{
		title:"北京",
		option:[""]
	},
	{
		title:"新疆",
		option:["乌鲁木齐"]
	},
	{
		title:"辽宁",
		option:["沈阳","大连","抚顺","盘锦","鞍山"]
	},
	{
		title:"湖南",
		option:["长沙","湘潭"]
	},
	{
		title:"河北",
		option:["石家庄","唐山","保定","沧州","秦皇岛","廊坊","邯郸"]
	},
	{
		title:"内蒙古",
		option:["呼和浩特","包头"]
	},
	{
		title:"天津",
		option:[""]
	},
	{
		title:"福建",
		option:["福州","厦门","泉州","漳州","宁德","龙岩"]
	},
	{
		title:"陕西",
		option:["西安","咸阳"]
	},
	{
		title:"浙江",
		option:["杭州","宁波","台州","温州","绍兴","金华"]
	},
	{
		title:"四川",
		option:["成都","绵阳"]
	},
	{
		title:"贵州",
		option:["贵阳","遵义"]
	},
	{
		title:"云南",
		option:["昆明"]
	},
	{
		title:"上海",
		option:[""]
	},
	{
		title:"山西",
		option:["太原","晋城","大同","临汾"]
	},
	{
		title:"江西",
		option:["南昌","九江","抚州","赣州"]
	},
	{
		title:"广西",
		option:["南宁","柳州","桂林"]
	},
	{
		title:"黑龙江",
		option:["哈尔滨","大庆"]
	},
	{
		title:"宁夏",
		option:["银川"]
	},
	{
		title:"江苏",
		option:["南京","盐城","徐州","宿迁","泰州","连云港","无锡","常州","扬州","苏州","镇江","淮安","南通"]
	},
	{
		title:"安徽",
		option:["合肥","蚌埠","淮南","芜湖","六安"]
	},
	{
		title:"吉林",
		option:["长春","吉林"]
	},
	{
		title:"湖北",
		option:["武汉","荆州","随州","宜昌","黄冈"]
	},
	{
		title:"重庆",
		option:["",""]
	},
	{
		title:"山东",
		option:["济南","威海","烟台","济宁","枣庄","临沂","潍坊","日照","青岛","淄博"]
	},
	{
		title:"河南",
		option:["郑州","安阳","新乡","洛阳","焦作","开封","商丘","许昌"]
	},
	{
		title:"广东",
		option:["广州","东莞","深圳","佛山"]
	}
];
function createCity(origin){
	var box=document.createElement("div"),
		title=document.createElement("h3"),
		pp=document.createElement("p");
	box.className="box";
	title.className="title";
	title.innerHTML=origin.title;	
	origin.option.forEach(function(item){
		var anchor=document.createElement("a");
		anchor.innerHTML=item;
		pp.appendChild(anchor);
	});
	box.appendChild(title);
	box.appendChild(pp);
	return box;
}
var cityFragment=document.createDocumentFragment();
cityData.forEach(function(item){
	cityFragment.appendChild(createCity(item));
});
document.getElementById("container").appendChild(cityFragment);